### ISSUE TITLE
Incorrect profile or LLM Hallucination?

### ISSUE THREAD

**Issue by jlewi** [jlewi/bsctl#14]
I got the following result.

```
    - account:
        handle: dye.bsky.social
        did: did:plc:xdn7eten3slw6cfp6a2qk4mt
      reason: The person describes their job role as 'platform engineer', which clearly indicates they belong to the Platform Engineer community.
```

But this person doesn't seem to have any description.

I suspect we have a bug in the prompt logic.

Here's the prompt
https://github.com/jlewi/bsctl/blob/9c8e1cdc1423e15dbaf306d879e744a20b5ca6d2/pkg/lists/profile_prompt.tmpl
https://github.com/jlewi/bskylists/blob/a976ef64c0221245989d8444df881696e17f7985/platform_community_builder.yaml

I suspect the user's profile is an empty string but not nil. As a result we don't skip classifying them here
https://github.com/jlewi/bsctl/pull/13/files#diff-095c3a68d18e3b44511fee80c1ad428949d494451f943d1f6263cec863c03c83R113

I suspect since the profile description is empty the model gets confused and uses the profile of the example.

I simple fix might be to check if the description is empty.
